# Setup
title:               rb
tagline:             'un blog'
description:         'In theory, there is no difference between practice and theory. In practice, there is.'
url:                 https://rbarbadillo.github.io
markdown:            kramdown
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Raquel Barbadillo
  url:               https://twitter.com/raquelbars
  email:             raquelbarbadillo@pm.me

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
