# Setup
title:               ~/rbv
tagline:             'notas'
description:         'que te importe y te esfuerces'
url:                 https://rbarbadillo.github.io
markdown:            kramdown
baseurl:             ''
pagination:          20
permalink:           pretty

# About/contact
author:
  name:              Raquel Barbadillo
  url:               https://twitter.com/raquelbars
  email:             raquelbarbadillo@pm.me

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed


# Custom vars
version:             1.1.0
