# Setup
title:               rb
tagline:             'un blog'
description:         'Integritas, consonantia et claritas.'
url:                 https://rbarbadillo.github.io
markdown:            kramdown
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Raquel Barbadillo
  url:               https://twitter.com/raquelbars
  email:             raquelbarbadillo@pm.me

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed


# Custom vars
version:             1.1.0
